/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Models/street_city.glb --output src/components/CityModel.tsx --types 
Author: Comicaroid (https://sketchfab.com/yuuuusukeeee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/street-city-bc1dcddc0fb94b54ad7c0dfdab596f51
Title: Street_[city]
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_6: THREE.Mesh
    Object_9: THREE.Mesh
    Object_11: THREE.Mesh
    Object_13: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_23: THREE.Mesh
    Object_25: THREE.Mesh
    Object_27: THREE.Mesh
    Object_29: THREE.Mesh
    Object_31: THREE.Mesh
    Object_33: THREE.Mesh
    Object_35: THREE.Mesh
    Object_37: THREE.Mesh
    Object_39: THREE.Mesh
    Object_41: THREE.Mesh
    Object_43: THREE.Mesh
    Object_45: THREE.Mesh
    Object_47: THREE.Mesh
    Object_49: THREE.Mesh
    Object_51: THREE.Mesh
    Object_53: THREE.Mesh
    Object_55: THREE.Mesh
    Object_57: THREE.Mesh
    Object_59: THREE.Mesh
    Object_61: THREE.Mesh
    Object_63: THREE.Mesh
    Object_65: THREE.Mesh
    Object_67: THREE.Mesh
    Object_69: THREE.Mesh
    Object_71: THREE.Mesh
    Object_73: THREE.Mesh
    Object_75: THREE.Mesh
    Object_77: THREE.Mesh
    Object_79: THREE.Mesh
    Object_83: THREE.Mesh
    Object_85: THREE.Mesh
    Object_88: THREE.Mesh
    Object_90: THREE.Mesh
    Object_92: THREE.Mesh
    Object_97: THREE.Mesh
    Object_99: THREE.Mesh
    Object_101: THREE.Mesh
    Object_103: THREE.Mesh
    Object_105: THREE.Mesh
    Object_108: THREE.Mesh
    Object_110: THREE.Mesh
    Object_112: THREE.Mesh
    Object_114: THREE.Mesh
    Object_116: THREE.Mesh
    Object_118: THREE.Mesh
    Object_120: THREE.Mesh
    Object_122: THREE.Mesh
    Object_124: THREE.Mesh
    Object_126: THREE.Mesh
    Object_128: THREE.Mesh
    Object_130: THREE.Mesh
    Object_132: THREE.Mesh
    Object_136: THREE.Mesh
    Object_139: THREE.Mesh
    Object_142: THREE.Mesh
    Object_144: THREE.Mesh
    Object_146: THREE.Mesh
    Object_148: THREE.Mesh
    Object_150: THREE.Mesh
    Object_152: THREE.Mesh
    Object_154: THREE.Mesh
    Object_156: THREE.Mesh
    Object_158: THREE.Mesh
    Object_160: THREE.Mesh
    Object_162: THREE.Mesh
    Object_164: THREE.Mesh
    Object_166: THREE.Mesh
    Object_168: THREE.Mesh
    Object_170: THREE.Mesh
    Object_172: THREE.Mesh
    Object_175: THREE.Mesh
    Object_177: THREE.Mesh
    Object_179: THREE.Mesh
    Object_181: THREE.Mesh
    Object_183: THREE.Mesh
    Object_185: THREE.Mesh
    Object_187: THREE.Mesh
    Object_189: THREE.Mesh
    Object_191: THREE.Mesh
    Object_193: THREE.Mesh
    Object_195: THREE.Mesh
    Object_197: THREE.Mesh
    Object_199: THREE.Mesh
    Object_201: THREE.Mesh
    Object_203: THREE.Mesh
    Object_205: THREE.Mesh
    Object_207: THREE.Mesh
    Object_210: THREE.Mesh
    Object_212: THREE.Mesh
    Object_214: THREE.Mesh
    Object_216: THREE.Mesh
    Object_218: THREE.Mesh
    Object_221: THREE.Mesh
    Object_223: THREE.Mesh
    Object_225: THREE.Mesh
    Object_227: THREE.Mesh
    Object_229: THREE.Mesh
    Object_231: THREE.Mesh
    Object_233: THREE.Mesh
    Object_235: THREE.Mesh
    Object_237: THREE.Mesh
    Object_239: THREE.Mesh
    Object_241: THREE.Mesh
    Object_243: THREE.Mesh
    Object_245: THREE.Mesh
    Object_247: THREE.Mesh
    Object_251: THREE.Mesh
    Object_254: THREE.Mesh
    Object_256: THREE.Mesh
    Object_258: THREE.Mesh
    Object_260: THREE.Mesh
    Object_262: THREE.Mesh
    Object_264: THREE.Mesh
    Object_266: THREE.Mesh
    Object_268: THREE.Mesh
    Object_270: THREE.Mesh
    Object_272: THREE.Mesh
    Object_274: THREE.Mesh
    Object_276: THREE.Mesh
    Object_278: THREE.Mesh
    Object_280: THREE.Mesh
    Object_282: THREE.Mesh
    Object_284: THREE.Mesh
    Object_286: THREE.Mesh
    Object_288: THREE.Mesh
    Object_290: THREE.Mesh
    Object_292: THREE.Mesh
    Object_294: THREE.Mesh
    Object_296: THREE.Mesh
    Object_298: THREE.Mesh
    Object_300: THREE.Mesh
    Object_302: THREE.Mesh
    Object_304: THREE.Mesh
    Object_306: THREE.Mesh
    Object_308: THREE.Mesh
    Object_310: THREE.Mesh
    Object_312: THREE.Mesh
    Object_314: THREE.Mesh
    Object_316: THREE.Mesh
    Object_318: THREE.Mesh
    Object_320: THREE.Mesh
    Object_322: THREE.Mesh
    Object_324: THREE.Mesh
    Object_326: THREE.Mesh
    Object_328: THREE.Mesh
    Object_330: THREE.Mesh
    Object_332: THREE.Mesh
    Object_334: THREE.Mesh
    Object_336: THREE.Mesh
    Object_338: THREE.Mesh
    Object_340: THREE.Mesh
    Object_342: THREE.Mesh
    Object_344: THREE.Mesh
    Object_346: THREE.Mesh
    Object_348: THREE.Mesh
    Object_350: THREE.Mesh
    Object_352: THREE.Mesh
    Object_354: THREE.Mesh
    Object_356: THREE.Mesh
    Object_358: THREE.Mesh
    Object_360: THREE.Mesh
    Object_362: THREE.Mesh
    Object_365: THREE.Mesh
    Object_367: THREE.Mesh
    Object_369: THREE.Mesh
    Object_371: THREE.Mesh
    Object_373: THREE.Mesh
    Object_375: THREE.Mesh
    Object_377: THREE.Mesh
    Object_379: THREE.Mesh
    Object_381: THREE.Mesh
    Object_383: THREE.Mesh
    Object_385: THREE.Mesh
    Object_387: THREE.Mesh
    Object_389: THREE.Mesh
    Object_391: THREE.Mesh
    Object_393: THREE.Mesh
    Object_395: THREE.Mesh
    Object_397: THREE.Mesh
    Object_399: THREE.Mesh
    Object_401: THREE.Mesh
    Object_403: THREE.Mesh
    Object_405: THREE.Mesh
    Object_407: THREE.Mesh
    Object_409: THREE.Mesh
    Object_411: THREE.Mesh
    Object_413: THREE.Mesh
    Object_415: THREE.Mesh
    Object_417: THREE.Mesh
    Object_419: THREE.Mesh
    Object_421: THREE.Mesh
    Object_423: THREE.Mesh
    Object_425: THREE.Mesh
    Object_427: THREE.Mesh
    Object_429: THREE.Mesh
    Object_431: THREE.Mesh
    Object_433: THREE.Mesh
    Object_435: THREE.Mesh
    Object_437: THREE.Mesh
    Object_439: THREE.Mesh
    Object_441: THREE.Mesh
    Object_443: THREE.Mesh
    Object_445: THREE.Mesh
    Object_447: THREE.Mesh
    Object_449: THREE.Mesh
    Object_451: THREE.Mesh
    Object_453: THREE.Mesh
    Object_455: THREE.Mesh
    Object_457: THREE.Mesh
    Object_459: THREE.Mesh
    Object_461: THREE.Mesh
    Object_463: THREE.Mesh
    Object_465: THREE.Mesh
    Object_467: THREE.Mesh
    Object_469: THREE.Mesh
    Object_471: THREE.Mesh
    Object_473: THREE.Mesh
    Object_475: THREE.Mesh
    Object_477: THREE.Mesh
    Object_479: THREE.Mesh
    Object_481: THREE.Mesh
    Object_483: THREE.Mesh
    Object_485: THREE.Mesh
    Object_487: THREE.Mesh
    Object_489: THREE.Mesh
    Object_491: THREE.Mesh
    Object_493: THREE.Mesh
    Object_495: THREE.Mesh
    Object_497: THREE.Mesh
    Object_499: THREE.Mesh
    Object_501: THREE.Mesh
    Object_503: THREE.Mesh
    Object_505: THREE.Mesh
    Object_507: THREE.Mesh
    Object_509: THREE.Mesh
    Object_511: THREE.Mesh
    Object_513: THREE.Mesh
    Object_515: THREE.Mesh
    Object_517: THREE.Mesh
    Object_519: THREE.Mesh
    Object_521: THREE.Mesh
    Object_523: THREE.Mesh
    Object_525: THREE.Mesh
    Object_527: THREE.Mesh
    Object_529: THREE.Mesh
    Object_531: THREE.Mesh
    Object_533: THREE.Mesh
    Object_535: THREE.Mesh
    Object_537: THREE.Mesh
    Object_539: THREE.Mesh
    Object_541: THREE.Mesh
    Object_543: THREE.Mesh
    Object_545: THREE.Mesh
    Object_547: THREE.Mesh
    Object_549: THREE.Mesh
    Object_551: THREE.Mesh
    Object_553: THREE.Mesh
    Object_555: THREE.Mesh
    Object_557: THREE.Mesh
    Object_559: THREE.Mesh
    Object_561: THREE.Mesh
    Object_563: THREE.Mesh
    Object_565: THREE.Mesh
    Object_567: THREE.Mesh
    Object_569: THREE.Mesh
    Object_571: THREE.Mesh
    Object_573: THREE.Mesh
    Object_575: THREE.Mesh
    Object_577: THREE.Mesh
    Object_579: THREE.Mesh
    Object_581: THREE.Mesh
    Object_583: THREE.Mesh
    Object_585: THREE.Mesh
    Object_587: THREE.Mesh
    Object_589: THREE.Mesh
    Object_591: THREE.Mesh
    Object_593: THREE.Mesh
    Object_595: THREE.Mesh
    Object_597: THREE.Mesh
    Object_599: THREE.Mesh
    Object_601: THREE.Mesh
    Object_603: THREE.Mesh
    Object_605: THREE.Mesh
    Object_607: THREE.Mesh
    Object_609: THREE.Mesh
    Object_611: THREE.Mesh
    Object_613: THREE.Mesh
    Object_615: THREE.Mesh
    Object_617: THREE.Mesh
    Object_619: THREE.Mesh
    Object_621: THREE.Mesh
    Object_623: THREE.Mesh
    Object_625: THREE.Mesh
    Object_627: THREE.Mesh
    Object_629: THREE.Mesh
    Object_631: THREE.Mesh
    Object_633: THREE.Mesh
    Object_635: THREE.Mesh
    Object_637: THREE.Mesh
    Object_639: THREE.Mesh
    Object_641: THREE.Mesh
    Object_643: THREE.Mesh
    Object_645: THREE.Mesh
    Object_647: THREE.Mesh
    Object_649: THREE.Mesh
    Object_651: THREE.Mesh
    Object_653: THREE.Mesh
    Object_655: THREE.Mesh
    Object_657: THREE.Mesh
    Object_659: THREE.Mesh
    Object_661: THREE.Mesh
    Object_663: THREE.Mesh
    Object_665: THREE.Mesh
    Object_667: THREE.Mesh
    Object_669: THREE.Mesh
    Object_671: THREE.Mesh
    Object_673: THREE.Mesh
    Object_675: THREE.Mesh
    Object_677: THREE.Mesh
    Object_679: THREE.Mesh
    Object_681: THREE.Mesh
    Object_683: THREE.Mesh
    Object_685: THREE.Mesh
    Object_687: THREE.Mesh
    Object_689: THREE.Mesh
    Object_691: THREE.Mesh
    Object_693: THREE.Mesh
    Object_695: THREE.Mesh
    Object_697: THREE.Mesh
    Object_699: THREE.Mesh
    Object_701: THREE.Mesh
    Object_703: THREE.Mesh
    Object_705: THREE.Mesh
    Object_707: THREE.Mesh
    Object_709: THREE.Mesh
    Object_711: THREE.Mesh
    Object_713: THREE.Mesh
    Object_715: THREE.Mesh
    Object_717: THREE.Mesh
    Object_719: THREE.Mesh
    Object_721: THREE.Mesh
    Object_723: THREE.Mesh
    Object_725: THREE.Mesh
    Object_727: THREE.Mesh
    Object_729: THREE.Mesh
    Object_731: THREE.Mesh
    Object_733: THREE.Mesh
    Object_735: THREE.Mesh
    Object_737: THREE.Mesh
    Object_739: THREE.Mesh
    Object_741: THREE.Mesh
    Object_743: THREE.Mesh
    Object_745: THREE.Mesh
    Object_747: THREE.Mesh
    Object_749: THREE.Mesh
    Object_751: THREE.Mesh
    Object_753: THREE.Mesh
    Object_755: THREE.Mesh
    Object_757: THREE.Mesh
    Object_759: THREE.Mesh
    Object_761: THREE.Mesh
    Object_763: THREE.Mesh
    Object_765: THREE.Mesh
    Object_767: THREE.Mesh
    Object_769: THREE.Mesh
    Object_771: THREE.Mesh
    Object_773: THREE.Mesh
    Object_775: THREE.Mesh
    Object_777: THREE.Mesh
    Object_779: THREE.Mesh
    Object_781: THREE.Mesh
    Object_783: THREE.Mesh
    Object_785: THREE.Mesh
    Object_787: THREE.Mesh
    Object_789: THREE.Mesh
    Object_791: THREE.Mesh
    Object_793: THREE.Mesh
    Object_795: THREE.Mesh
    Object_797: THREE.Mesh
    Object_799: THREE.Mesh
    Object_801: THREE.Mesh
    Object_803: THREE.Mesh
    Object_805: THREE.Mesh
    Object_807: THREE.Mesh
    Object_809: THREE.Mesh
    Object_811: THREE.Mesh
    Object_814: THREE.Mesh
    Object_816: THREE.Mesh
    Object_817: THREE.Mesh
  }
  materials: {
    color_darkgGrey: THREE.MeshStandardMaterial
    color_grey: THREE.MeshStandardMaterial
    color_lightGrey: THREE.MeshStandardMaterial
    color_white: THREE.MeshStandardMaterial
    color_blk: THREE.MeshStandardMaterial
    color_yellow: THREE.MeshStandardMaterial
    color_lightBlue: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/Models/street_city.glb') as any
  return (
    <group {...props} dispose={null}>
      <group position={[15.675, 0, 42.743]} scale={0.001}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.color_darkgGrey} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.color_grey} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.color_grey} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.color_grey} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_69.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_75.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.color_white} />
      </group>
      <group position={[15.675, 0, 42.743]} scale={0.001}>
        <mesh geometry={nodes.Object_83.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_85.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_88.geometry} material={materials.color_darkgGrey} />
        <mesh geometry={nodes.Object_90.geometry} material={materials.color_darkgGrey} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.color_darkgGrey} />
        <mesh geometry={nodes.Object_97.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_99.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_101.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_103.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_105.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_108.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_110.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_112.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_114.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_116.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_118.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_120.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_122.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_124.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_126.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_128.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_130.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_132.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_136.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_139.geometry} material={materials.color_blk} />
        <mesh geometry={nodes.Object_142.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_144.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_146.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_148.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_150.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_152.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_154.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_156.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_158.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_160.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_162.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_164.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_166.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_168.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_170.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_172.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_175.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_177.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_179.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_181.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_183.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_185.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_187.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_189.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_191.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_193.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_195.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_197.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_199.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_201.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_203.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_205.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_207.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_210.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_212.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_214.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_216.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_218.geometry} material={materials.color_white} />
        <mesh geometry={nodes.Object_221.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_223.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_225.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_227.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_229.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_231.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_233.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_235.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_237.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_239.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_241.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_243.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_245.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_247.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_251.geometry} material={materials.color_yellow} />
        <mesh geometry={nodes.Object_254.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_256.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_258.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_260.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_262.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_264.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_266.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_268.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_270.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_272.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_274.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_276.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_278.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_280.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_282.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_284.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_286.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_288.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_290.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_292.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_294.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_296.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_298.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_300.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_302.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_304.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_306.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_308.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_310.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_312.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_314.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_316.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_318.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_320.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_322.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_324.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_326.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_328.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_330.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_332.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_334.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_336.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_338.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_340.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_342.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_344.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_346.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_348.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_350.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_352.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_354.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_356.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_358.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_360.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_362.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_365.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_367.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_369.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_371.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_373.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_375.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_377.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_379.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_381.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_383.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_385.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_387.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_389.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_391.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_393.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_395.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_397.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_399.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_401.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_403.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_405.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_407.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_409.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_411.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_413.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_415.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_417.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_419.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_421.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_423.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_425.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_427.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_429.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_431.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_433.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_435.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_437.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_439.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_441.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_443.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_445.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_447.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_449.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_451.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_453.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_455.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_457.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_459.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_461.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_463.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_465.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_467.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_469.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_471.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_473.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_475.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_477.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_479.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_481.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_483.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_485.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_487.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_489.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_491.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_493.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_495.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_497.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_499.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_501.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_503.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_505.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_507.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_509.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_511.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_513.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_515.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_517.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_519.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_521.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_523.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_525.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_527.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_529.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_531.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_533.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_535.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_537.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_539.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_541.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_543.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_545.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_547.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_549.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_551.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_553.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_555.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_557.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_559.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_561.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_563.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_565.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_567.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_569.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_571.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_573.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_575.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_577.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_579.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_581.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_583.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_585.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_587.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_589.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_591.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_593.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_595.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_597.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_599.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_601.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_603.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_605.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_607.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_609.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_611.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_613.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_615.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_617.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_619.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_621.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_623.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_625.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_627.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_629.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_631.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_633.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_635.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_637.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_639.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_641.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_643.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_645.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_647.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_649.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_651.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_653.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_655.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_657.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_659.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_661.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_663.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_665.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_667.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_669.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_671.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_673.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_675.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_677.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_679.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_681.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_683.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_685.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_687.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_689.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_691.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_693.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_695.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_697.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_699.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_701.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_703.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_705.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_707.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_709.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_711.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_713.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_715.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_717.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_719.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_721.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_723.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_725.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_727.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_729.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_731.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_733.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_735.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_737.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_739.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_741.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_743.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_745.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_747.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_749.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_751.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_753.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_755.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_757.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_759.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_761.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_763.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_765.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_767.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_769.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_771.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_773.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_775.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_777.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_779.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_781.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_783.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_785.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_787.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_789.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_791.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_793.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_795.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_797.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_799.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_801.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_803.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_805.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_807.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_809.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_811.geometry} material={materials.color_lightBlue} />
        <mesh geometry={nodes.Object_814.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_816.geometry} material={materials.color_lightGrey} />
        <mesh geometry={nodes.Object_817.geometry} material={materials.color_lightGrey} />
      </group>
    </group>
  )
}

useGLTF.preload('/street_city.glb')
